-- ============================================================
-- Caliper — schema v3: per-org wrapped data-encryption keys
-- Envelope encryption: each org's DEK is generated by AWS KMS and
-- stored here ONLY in wrapped (KMS-encrypted) form. Unwrapping
-- happens inside the getdek edge function via KMS Decrypt.
-- Offboarding a tenant = schedule their KMS key material for
-- deletion = their data is cryptographically shredded.
-- ============================================================

create table org_keys (
  org_id      uuid primary key references orgs(id) on delete cascade,
  wrapped_dek bytea not null,        -- KMS CiphertextBlob, never plaintext
  kms_key_id  text not null,
  created_at  timestamptz default now()
);

-- deny-by-default: NO policies on purpose. End users can never touch
-- this table; only the service role (inside getdek) reads/writes it.
alter table org_keys enable row level security;
